# Generated by Django 3.2.7 on 2022-02-14 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='nickname',
        ),
    ]
