# Generated by Django 3.2.7 on 2022-06-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_rename_user_video_channel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='channel_name',
        ),
    ]
